In [18]:
import AnalyzeMany as AM
import GenManyOnUnity3 as GM
import parameters_text as PT
import numpy as np
import re


ModuleNotFoundError: No module named 'ROOT'

In [19]:
LambdaInfo = {'bounds':(1000, 2000), # GeV
                'delta': 500}
geffInfo = {'bounds':(0.17, 0.18),
            'delta': 0.0050}

paramGrid = []

L = LambdaInfo['bounds'][0]
g = geffInfo['bounds'][0]

while L <= LambdaInfo['bounds'][1]:
    # print(L)
    sameLlist = []
    g = geffInfo['bounds'][0]
    while g <= geffInfo['bounds'][1]:
        # print(g)
        sameLlist.append([L,g])
        g += geffInfo['delta']
        g = round(g,3)
        # print(g)
    paramGrid.append(sameLlist)
    L += LambdaInfo['delta']

paramGrid = np.array(paramGrid)
print(paramGrid)

NameError: name 'np' is not defined

In [20]:
for LSet in paramGrid:
    # print(LSet)
    for gSet in LSet:
        thisPath = f"/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_{int(gSet[0])}_{('{:.3f}'.format(gSet[1]))[2:]}"

        # then run ls to get all the run files
        # then format the run string
        # then run analysis
        # Pull significance and put into array


In [21]:
TheString = """Events remaining after each cut group
32
4
4
2
2
num eejj events b4 cuts: 4
2
32
Efficiency: 0.0625"""

eff = TheString.split('\n')[-1][12:]
print(eff)

0.0625


In [22]:
TheString = """abcdef"""

eff = re.search('(?<=abc)def',TheString)
print(eff)

NameError: name 're' is not defined

In [23]:
test = [0.1, 3.4, 0.08]

for n in test:
    print('_'.join('{:.3f}'.format(n).split('.')))


0_100
3_400
0_080


In [24]:
LambdaInfo = {'bounds':(1000, 5e3), # GeV
                'delta': 500}
geffInfo = {'bounds':(0.1, 1.1), 
            'delta': 0.2}
print('starting ')
# clear_writeFile()
print(geffInfo['bounds'][0]*1000, (geffInfo['bounds'][1]+ geffInfo['delta'])*1000, geffInfo['delta']*1000, sep='\n')
Lcols = [l for l in range(LambdaInfo['bounds'][0], int(LambdaInfo['bounds'][1]+ LambdaInfo['delta']), LambdaInfo['delta'])]
gRows = [g/1000 for g in range(int(geffInfo['bounds'][0]*1000), int((geffInfo['bounds'][1]+ geffInfo['delta'])*1000), int(geffInfo['delta']*1000))]
# analyzeThis('LNVF_1000_170')
print(Lcols)
print(gRows)

starting 
100.0
1300.0
200.0
[1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000]
[0.1, 0.3, 0.5, 0.7, 0.9, 1.1]


In [25]:
import AnalyzeMany as AM

AM.run_command('ls')

ModuleNotFoundError: No module named 'ROOT'

In [26]:
import ParamSpAnalyzer as PSAnal
import Param_space_explorer as PSEx
import AnalyzeMany as AM
start_dir = '/Users/dysonk/Work/temp/PspaceSkipChecker/'

LambdaInfo = {'bounds':(1000, 5e3), # GeV
                'delta': 500}
geffInfo = {'bounds':(0.1, 1.1), 
            'delta': 0.2}

LambdaInfo = PSEx.set_start(LambdaInfo)
geffInfo = PSEx.set_start(geffInfo)

while LambdaInfo['current'] <= LambdaInfo['bounds'][1]:
    
    # print("Lambda: ", LambdaInfo['current'])
    geffInfo = PSEx.set_start(geffInfo)
    while geffInfo['current'] <= geffInfo['bounds'][1]:
        thisFolderName = PSAnal.fileNameMaker(LambdaInfo['current'], geffInfo['current'])
        AM.run_command('mkdir ' + start_dir + thisFolderName)
        for i in range(5):
            AM.run_command('mkdir ' + start_dir + thisFolderName + '/run_0'+ str(i+1))
            thisFileName = start_dir + thisFolderName + f"/run_0{str(i+1)}/delphes_events.dat"
            # AM.run_command('touch ' + thisFileName)
            # print(AM.run_command('ls '+ start_dir + thisFolderName + '/run_0'+ str(i+1)))
            # file1 = open(thisFileName)
            with open(thisFileName, 'w') as file:
                file.write(str(3000))
        geffInfo = PSEx.incrementParam(geffInfo)
    LambdaInfo = PSEx.incrementParam(LambdaInfo)


ModuleNotFoundError: No module named 'ROOT'

In [27]:
def getPreExistingFolders(start_d):
    fromls = AM.run_command('ls ' + start_d)
    # print(fromls.split)
    # print([str(b) for b in fromls.split()])
    # if fromls[0] != 'L':
    #     # then we are not looking good
    #     print("no processes at all")
    #     return []
    # else:
    runlist = [r[5:-6] for r in fromls.split()]
    # print([r[5:-6] for r in runlist])
    # print(runlist)
    return runlist
    
def get_runs(sd, foldername):
    # n_runfolders = 0
    runlist = [r[5:-6] for r in AM.run_command('ls ' + sd + foldername).split()]
    n_runfolders = len(runlist)
    n_runs = 0
    if not n_runfolders:
        return 0
    else:
        events = []
        for run in runlist: 
            with open(sd+foldername+ run + '/delphes_events.dat', 'r') as fl:
                events = fl.readlines()
                events = int(events[0])
            if events>=3000:
                n_runs += 1
    return n_runs 

def checkPreexistingProc(L, g):
    newFolderName = PSAnal.fileNameMaker(L, g)
    preexistingFolders = getPreExistingFolders(start_dir)
    alreadyExists = False
    for folder in preexistingFolders:
        if newFolderName == folder:
            alreadyExists = True
    
    if not alreadyExists:
        return 0
    else:
        return get_runs(start_dir, newFolderName+'/')

In [28]:
LambdaInfo = PSEx.set_start(LambdaInfo)
geffInfo = PSEx.set_start(geffInfo)
# LambdaInfo = PSEx.set_start(LambdaInfo)
# geffInfo = PSEx.set_start(geffInfo)

while LambdaInfo['current'] <= LambdaInfo['bounds'][1]:
    
    # print("Lambda: ", LambdaInfo['current'])
    geffInfo = PSEx.set_start(geffInfo)
    while geffInfo['current'] <= geffInfo['bounds'][1]:
        nruns = checkPreexistingProc(LambdaInfo['current'], geffInfo['current'])
        print(nruns)
        geffInfo = PSEx.incrementParam(geffInfo)
    LambdaInfo = PSEx.incrementParam(LambdaInfo)


NameError: name 'PSEx' is not defined

In [29]:
LambdaInfo = {'bounds':(1000, 5e3), # GeV
                'delta': 500/4}
geffInfo = {'bounds':(0.1, 1.1), 
            'delta': 0.2/4}

LambdaInfo = PSEx.set_start(LambdaInfo)
geffInfo = PSEx.set_start(geffInfo)

while LambdaInfo['current'] <= LambdaInfo['bounds'][1]:
    
    # print("Lambda: ", LambdaInfo['current'])
    geffInfo = PSEx.set_start(geffInfo)
    while geffInfo['current'] <= geffInfo['bounds'][1]:
        nruns = checkPreexistingProc(LambdaInfo['current'], geffInfo['current'])
        # print(nruns)
        how_many_runs = 5 - nruns
        print(f"{LambdaInfo['current']}, {geffInfo['current']}: {how_many_runs}")
        geffInfo = PSEx.incrementParam(geffInfo)
    LambdaInfo = PSEx.incrementParam(LambdaInfo)

NameError: name 'PSEx' is not defined

In [30]:
test = 'abcdefg'
print(test[-3:])

efg


In [31]:
import numpy as np
def incrementParam(info):
    newinfo = info
    newinfo.update({'current': round(info['current']+ info['delta'], ndigits=5)})
    return newinfo

def set_start(dict):
    # print(dict)
    newdict = dict
    newdict.update({'current': dict['bounds'][0]})
    return newdict



In [32]:
def make_safe_grid():
    LI = {'bounds':(1000, 5e3), # GeV
                'delta': 500/2}
    gI = {'bounds':(0.1, 1.1), 
                'delta': 0.2/2}
    LI = set_start(LI)
    gI = set_start(gI)
    outlist = []
    while LI['current'] <= LI['bounds'][1]:
        
        # print("Lambda: ", LambdaInfo['current'])
        geffInfo = set_start(gI)
        templist = []
        while gI['current'] <= gI['bounds'][1]:
            outlist.append((LI['current'], gI['current']))
            gI = incrementParam(gI)
        # outlist.append(templist)
        LI = incrementParam(LI)
    return np.array(outlist)

def in_safe_grid(LI, GI, s_grid):
    print(f"checking whether to delete {LI['current'], GI['current']} runs")
    in_grid = False
    # print(s_grid)
    for pair in s_grid:
        # print(pair)
        # print(np.array((LI['current'], GI['current'])))
        # print((np.array((LI['current'], GI['current'])) == pair).all())
        if (np.array((LI['current'], GI['current'])) == pair).all():
            # print("hi")
            in_grid = True
    return in_grid

def remove_runs(LI, gi):
    AM.run_command(f"rm -vr /work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/{PSAnal.fileNameMaker(LI, gi)}")


LambdaInfo = set_start(LambdaInfo)
geffInfo = set_start(geffInfo)




In [33]:
LambdaInfo = {'bounds':(1000, 5e3), # GeV
                  'delta': 500/4}
geffInfo = {'bounds':(0.1, 1.1), 
            'delta': 0.2/4}

LambdaInfo = set_start(LambdaInfo)
geffInfo = set_start(geffInfo)
print(LambdaInfo)
sgrid = make_safe_grid()

while LambdaInfo['current'] <= LambdaInfo['bounds'][1]:
        
        # print("Lambda: ", LambdaInfo['current'])
    geffInfo = set_start(geffInfo)
    # templist = []
    while geffInfo['current'] <= geffInfo['bounds'][1]:
        # outlist.append((LambdaInfo['current'], geffInfo['current']))
        # print(LambdaInfo['current'], geffInfo['current'])
        print(in_safe_grid(LambdaInfo, geffInfo, sgrid))
        geffInfo = incrementParam(geffInfo)
    # outlist.append(templist)
    LambdaInfo = incrementParam(LambdaInfo)
    # return np.array(outlist)

{'bounds': (1000, 5000.0), 'delta': 125.0, 'current': 1000}
checking whether to delete (1000, 0.1) runs
True
checking whether to delete (1000, 0.15) runs
False
checking whether to delete (1000, 0.2) runs
True
checking whether to delete (1000, 0.25) runs
False
checking whether to delete (1000, 0.3) runs
True
checking whether to delete (1000, 0.35) runs
False
checking whether to delete (1000, 0.4) runs
True
checking whether to delete (1000, 0.45) runs
False
checking whether to delete (1000, 0.5) runs
True
checking whether to delete (1000, 0.55) runs
False
checking whether to delete (1000, 0.6) runs
True
checking whether to delete (1000, 0.65) runs
False
checking whether to delete (1000, 0.7) runs
True
checking whether to delete (1000, 0.75) runs
False
checking whether to delete (1000, 0.8) runs
True
checking whether to delete (1000, 0.85) runs
False
checking whether to delete (1000, 0.9) runs
True
checking whether to delete (1000, 0.95) runs
False
checking whether to delete (1000, 1.0) r

In [34]:
outstring = '''Events remaining after each cut group
211602
27782
23177
12049
8984
num eejj events b4 cuts: 14336
8984
212412
Efficiency: 0.04229516
N_fin: 8984'''

N_fin = outstring.split('\n')[-1][7:]
print(N_fin)

8984


In [35]:
with open('ParamSpEff.dat', 'r') as file:
        lines = file.readlines()
        # print(lines)
        # proclines = [[float(line.strip().split(' ')[i]) if i<2 else int(line.strip().split(' ')[i]) for i in range(len(line.strip().split(' ')))] for line in lines]
        proclines = np.array([[float(line.strip().split(' ')[i]) for i in range(len(line.strip().split(' ')))] for line in lines])
        print(proclines)
        # [float(num) for num in line.strip().split for line in lines]

[[1.000000e+03 1.000000e-01 1.996748e-01]
 [1.000000e+03 1.500000e-01 2.155526e-01]
 [1.000000e+03 2.000000e-01 2.260592e-01]
 ...
 [5.000000e+03 1.000000e+00 2.380063e-01]
 [5.000000e+03 1.050000e+00 2.446758e-01]
 [5.000000e+03 1.100000e+00 2.379710e-01]]
