In [20]:
import AnalyzeMany as AM
import GenManyOnUnity3 as GM
import parameters_text as PT
import numpy as np
import re


In [16]:
LambdaInfo = {'bounds':(1000, 2000), # GeV
                'delta': 500}
geffInfo = {'bounds':(0.17, 0.18),
            'delta': 0.0050}

paramGrid = []

L = LambdaInfo['bounds'][0]
g = geffInfo['bounds'][0]

while L <= LambdaInfo['bounds'][1]:
    # print(L)
    sameLlist = []
    g = geffInfo['bounds'][0]
    while g <= geffInfo['bounds'][1]:
        # print(g)
        sameLlist.append([L,g])
        g += geffInfo['delta']
        g = round(g,3)
        # print(g)
    paramGrid.append(sameLlist)
    L += LambdaInfo['delta']

paramGrid = np.array(paramGrid)
print(paramGrid)

[[[1.00e+03 1.70e-01]
  [1.00e+03 1.75e-01]
  [1.00e+03 1.80e-01]]

 [[1.50e+03 1.70e-01]
  [1.50e+03 1.75e-01]
  [1.50e+03 1.80e-01]]

 [[2.00e+03 1.70e-01]
  [2.00e+03 1.75e-01]
  [2.00e+03 1.80e-01]]]


In [ ]:
for LSet in paramGrid:
    # print(LSet)
    for gSet in LSet:
        thisPath = f"/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_{int(gSet[0])}_{('{:.3f}'.format(gSet[1]))[2:]}"

        # then run ls to get all the run files
        # then format the run string
        # then run analysis
        # Pull significance and put into array


/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1000_170
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1000_175
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1000_180
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1500_170
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1500_175
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1500_180
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_2000_170
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_2000_175
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_2000_180


In [34]:
TheString = """Events remaining after each cut group
32
4
4
2
2
num eejj events b4 cuts: 4
2
32
Efficiency: 0.0625"""

eff = TheString.split('\n')[-1][12:]
print(eff)

0.0625


In [28]:
TheString = """abcdef"""

eff = re.search('(?<=abc)def',TheString)
print(eff)

<re.Match object; span=(3, 6), match='def'>
