In [20]:
import AnalyzeMany as AM
import GenManyOnUnity3 as GM
import parameters_text as PT
import numpy as np
import re


In [16]:
LambdaInfo = {'bounds':(1000, 2000), # GeV
                'delta': 500}
geffInfo = {'bounds':(0.17, 0.18),
            'delta': 0.0050}

paramGrid = []

L = LambdaInfo['bounds'][0]
g = geffInfo['bounds'][0]

while L <= LambdaInfo['bounds'][1]:
    # print(L)
    sameLlist = []
    g = geffInfo['bounds'][0]
    while g <= geffInfo['bounds'][1]:
        # print(g)
        sameLlist.append([L,g])
        g += geffInfo['delta']
        g = round(g,3)
        # print(g)
    paramGrid.append(sameLlist)
    L += LambdaInfo['delta']

paramGrid = np.array(paramGrid)
print(paramGrid)

[[[1.00e+03 1.70e-01]
  [1.00e+03 1.75e-01]
  [1.00e+03 1.80e-01]]

 [[1.50e+03 1.70e-01]
  [1.50e+03 1.75e-01]
  [1.50e+03 1.80e-01]]

 [[2.00e+03 1.70e-01]
  [2.00e+03 1.75e-01]
  [2.00e+03 1.80e-01]]]


In [ ]:
for LSet in paramGrid:
    # print(LSet)
    for gSet in LSet:
        thisPath = f"/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_{int(gSet[0])}_{('{:.3f}'.format(gSet[1]))[2:]}"

        # then run ls to get all the run files
        # then format the run string
        # then run analysis
        # Pull significance and put into array


/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1000_170
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1000_175
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1000_180
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1500_170
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1500_175
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1500_180
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_2000_170
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_2000_175
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_2000_180


In [34]:
TheString = """Events remaining after each cut group
32
4
4
2
2
num eejj events b4 cuts: 4
2
32
Efficiency: 0.0625"""

eff = TheString.split('\n')[-1][12:]
print(eff)

0.0625


In [28]:
TheString = """abcdef"""

eff = re.search('(?<=abc)def',TheString)
print(eff)

<re.Match object; span=(3, 6), match='def'>


In [43]:
test = [0.1, 3.4, 0.08]

for n in test:
    print('_'.join('{:.3f}'.format(n).split('.')))


0_100
3_400
0_080


In [ ]:
LambdaInfo = {'bounds':(1000, 5e3), # GeV
                'delta': 500}
geffInfo = {'bounds':(0.1, 1.1), 
            'delta': 0.2}
print('starting ')
# clear_writeFile()
print(geffInfo['bounds'][0]*1000, (geffInfo['bounds'][1]+ geffInfo['delta'])*1000, geffInfo['delta']*1000, sep='\n')
Lcols = [l for l in range(LambdaInfo['bounds'][0], int(LambdaInfo['bounds'][1]+ LambdaInfo['delta']), LambdaInfo['delta'])]
gRows = [g/1000 for g in range(int(geffInfo['bounds'][0]*1000), int((geffInfo['bounds'][1]+ geffInfo['delta'])*1000), int(geffInfo['delta']*1000))]
# analyzeThis('LNVF_1000_170')
print(Lcols)
print(gRows)

starting 
100.0
1300.0
200.0
[1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000]
[0.1, 0.3, 0.5, 0.7, 0.9, 1.1]


In [47]:
import AnalyzeMany as AM

AM.run_command('ls')

'AnalyzeMany.py\nAnalyzeMany.sh\n\x1bComparisonPlotTables\x1b[m\x1b[m\n\x1bGang_JetFake\x1b[m\x1b[m\nGenManyOnUnity2.py\nGenManyOnUnity3.py\nHistos.ipynb\n\x1bJetFake\x1b[m\x1b[m\n\x1bME5_debug\x1b[m\x1b[m\nMWjl1Comparison.png\nMWjl2Comparison.png\nMWjllComparison.png\nMakefile\nParamEx.sh\nParamSpAnalyzer.ipynb\nParamSpAnalyzer.py\nParamSpEff.dat\nParam_space_explorer.py\nRunAndSuchShortcuts.txt\n\x1b__pycache__\x1b[m\x1b[m\ncombineHistos.py\nhisto_editing.py\nparameters_text.py\nproc_text.py\nproc_text.txt\nread_many2.py\n\x1bread_root_file\x1b[m\x1b[m\nread_root_file.cpp\nread_root_file.o\nrootouttesting.root\ntest.dat\ntest.py\ntestplot.py\n'