In [20]:
import AnalyzeMany as AM
import GenManyOnUnity3 as GM
import parameters_text as PT
import numpy as np
import re


In [16]:
LambdaInfo = {'bounds':(1000, 2000), # GeV
                'delta': 500}
geffInfo = {'bounds':(0.17, 0.18),
            'delta': 0.0050}

paramGrid = []

L = LambdaInfo['bounds'][0]
g = geffInfo['bounds'][0]

while L <= LambdaInfo['bounds'][1]:
    # print(L)
    sameLlist = []
    g = geffInfo['bounds'][0]
    while g <= geffInfo['bounds'][1]:
        # print(g)
        sameLlist.append([L,g])
        g += geffInfo['delta']
        g = round(g,3)
        # print(g)
    paramGrid.append(sameLlist)
    L += LambdaInfo['delta']

paramGrid = np.array(paramGrid)
print(paramGrid)

[[[1.00e+03 1.70e-01]
  [1.00e+03 1.75e-01]
  [1.00e+03 1.80e-01]]

 [[1.50e+03 1.70e-01]
  [1.50e+03 1.75e-01]
  [1.50e+03 1.80e-01]]

 [[2.00e+03 1.70e-01]
  [2.00e+03 1.75e-01]
  [2.00e+03 1.80e-01]]]


In [ ]:
for LSet in paramGrid:
    # print(LSet)
    for gSet in LSet:
        thisPath = f"/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_{int(gSet[0])}_{('{:.3f}'.format(gSet[1]))[2:]}"

        # then run ls to get all the run files
        # then format the run string
        # then run analysis
        # Pull significance and put into array


/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1000_170
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1000_175
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1000_180
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1500_170
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1500_175
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_1500_180
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_2000_170
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_2000_175
/work/pi_mjrm_umass_edu/LNV_collider/Generated/Signal/LNVF_2000_180


In [34]:
TheString = """Events remaining after each cut group
32
4
4
2
2
num eejj events b4 cuts: 4
2
32
Efficiency: 0.0625"""

eff = TheString.split('\n')[-1][12:]
print(eff)

0.0625


In [28]:
TheString = """abcdef"""

eff = re.search('(?<=abc)def',TheString)
print(eff)

<re.Match object; span=(3, 6), match='def'>


In [43]:
test = [0.1, 3.4, 0.08]

for n in test:
    print('_'.join('{:.3f}'.format(n).split('.')))


0_100
3_400
0_080


In [ ]:
LambdaInfo = {'bounds':(1000, 5e3), # GeV
                'delta': 500}
geffInfo = {'bounds':(0.1, 1.1), 
            'delta': 0.2}
print('starting ')
# clear_writeFile()
print(geffInfo['bounds'][0]*1000, (geffInfo['bounds'][1]+ geffInfo['delta'])*1000, geffInfo['delta']*1000, sep='\n')
Lcols = [l for l in range(LambdaInfo['bounds'][0], int(LambdaInfo['bounds'][1]+ LambdaInfo['delta']), LambdaInfo['delta'])]
gRows = [g/1000 for g in range(int(geffInfo['bounds'][0]*1000), int((geffInfo['bounds'][1]+ geffInfo['delta'])*1000), int(geffInfo['delta']*1000))]
# analyzeThis('LNVF_1000_170')
print(Lcols)
print(gRows)

starting 
100.0
1300.0
200.0
[1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000]
[0.1, 0.3, 0.5, 0.7, 0.9, 1.1]


In [47]:
import AnalyzeMany as AM

AM.run_command('ls')

'AnalyzeMany.py\nAnalyzeMany.sh\n\x1bComparisonPlotTables\x1b[m\x1b[m\n\x1bGang_JetFake\x1b[m\x1b[m\nGenManyOnUnity2.py\nGenManyOnUnity3.py\nHistos.ipynb\n\x1bJetFake\x1b[m\x1b[m\n\x1bME5_debug\x1b[m\x1b[m\nMWjl1Comparison.png\nMWjl2Comparison.png\nMWjllComparison.png\nMakefile\nParamEx.sh\nParamSpAnalyzer.ipynb\nParamSpAnalyzer.py\nParamSpEff.dat\nParam_space_explorer.py\nRunAndSuchShortcuts.txt\n\x1b__pycache__\x1b[m\x1b[m\ncombineHistos.py\nhisto_editing.py\nparameters_text.py\nproc_text.py\nproc_text.txt\nread_many2.py\n\x1bread_root_file\x1b[m\x1b[m\nread_root_file.cpp\nread_root_file.o\nrootouttesting.root\ntest.dat\ntest.py\ntestplot.py\n'

In [ ]:
import ParamSpAnalyzer as PSAnal
import Param_space_explorer as PSEx
import AnalyzeMany as AM
start_dir = '/Users/dysonk/Work/temp/PspaceSkipChecker/'

LambdaInfo = {'bounds':(1000, 5e3), # GeV
                'delta': 500}
geffInfo = {'bounds':(0.1, 1.1), 
            'delta': 0.2}

LambdaInfo = PSEx.set_start(LambdaInfo)
geffInfo = PSEx.set_start(geffInfo)

while LambdaInfo['current'] <= LambdaInfo['bounds'][1]:
    
    # print("Lambda: ", LambdaInfo['current'])
    geffInfo = PSEx.set_start(geffInfo)
    while geffInfo['current'] <= geffInfo['bounds'][1]:
        thisFolderName = PSAnal.fileNameMaker(LambdaInfo['current'], geffInfo['current'])
        AM.run_command('mkdir ' + start_dir + thisFolderName)
        for i in range(5):
            AM.run_command('mkdir ' + start_dir + thisFolderName + '/run_0'+ str(i+1))
            thisFileName = start_dir + thisFolderName + f"/run_0{str(i+1)}/delphes_events.dat"
            # AM.run_command('touch ' + thisFileName)
            # print(AM.run_command('ls '+ start_dir + thisFolderName + '/run_0'+ str(i+1)))
            # file1 = open(thisFileName)
            with open(thisFileName, 'w') as file:
                file.write(str(3000))
        geffInfo = PSEx.incrementParam(geffInfo)
    LambdaInfo = PSEx.incrementParam(LambdaInfo)


In [ ]:
def getPreExistingFolders(start_d):
    fromls = AM.run_command('ls ' + start_d)
    # print(fromls.split)
    # print([str(b) for b in fromls.split()])
    # if fromls[0] != 'L':
    #     # then we are not looking good
    #     print("no processes at all")
    #     return []
    # else:
    runlist = [r[5:-6] for r in fromls.split()]
    # print([r[5:-6] for r in runlist])
    # print(runlist)
    return runlist
    
def get_runs(sd, foldername):
    # n_runfolders = 0
    runlist = [r[5:-6] for r in AM.run_command('ls ' + sd + foldername).split()]
    n_runfolders = len(runlist)
    n_runs = 0
    if not n_runfolders:
        return 0
    else:
        events = []
        for run in runlist: 
            with open(sd+foldername+ run + '/delphes_events.dat', 'r') as fl:
                events = fl.readlines()
                events = int(events[0])
            if events>=3000:
                n_runs += 1
    return n_runs 

def checkPreexistingProc(L, g):
    newFolderName = PSAnal.fileNameMaker(L, g)
    preexistingFolders = getPreExistingFolders(start_dir)
    alreadyExists = False
    for folder in preexistingFolders:
        if newFolderName == folder:
            alreadyExists = True
    
    if not alreadyExists:
        return 0
    else:
        return get_runs(start_dir, newFolderName+'/')

In [53]:
LambdaInfo = PSEx.set_start(LambdaInfo)
geffInfo = PSEx.set_start(geffInfo)
# LambdaInfo = PSEx.set_start(LambdaInfo)
# geffInfo = PSEx.set_start(geffInfo)

while LambdaInfo['current'] <= LambdaInfo['bounds'][1]:
    
    # print("Lambda: ", LambdaInfo['current'])
    geffInfo = PSEx.set_start(geffInfo)
    while geffInfo['current'] <= geffInfo['bounds'][1]:
        nruns = checkPreexistingProc(LambdaInfo['current'], geffInfo['current'])
        print(nruns)
        geffInfo = PSEx.incrementParam(geffInfo)
    LambdaInfo = PSEx.incrementParam(LambdaInfo)


4
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5


In [55]:
LambdaInfo = {'bounds':(1000, 5e3), # GeV
                'delta': 500/4}
geffInfo = {'bounds':(0.1, 1.1), 
            'delta': 0.2/4}

LambdaInfo = PSEx.set_start(LambdaInfo)
geffInfo = PSEx.set_start(geffInfo)

while LambdaInfo['current'] <= LambdaInfo['bounds'][1]:
    
    # print("Lambda: ", LambdaInfo['current'])
    geffInfo = PSEx.set_start(geffInfo)
    while geffInfo['current'] <= geffInfo['bounds'][1]:
        nruns = checkPreexistingProc(LambdaInfo['current'], geffInfo['current'])
        # print(nruns)
        how_many_runs = 5 - nruns
        print(f"{LambdaInfo['current']}, {geffInfo['current']}: {how_many_runs}")
        geffInfo = PSEx.incrementParam(geffInfo)
    LambdaInfo = PSEx.incrementParam(LambdaInfo)

1000, 0.1: 2
1000, 0.15: 5
1000, 0.2: 5
1000, 0.25: 5
1000, 0.3: 0
1000, 0.35: 5
1000, 0.4: 5
1000, 0.45: 5
1000, 0.5: 0
1000, 0.55: 5
1000, 0.6: 5
1000, 0.65: 5
1000, 0.7: 0
1000, 0.75: 5
1000, 0.8: 5
1000, 0.85: 5
1000, 0.9: 0
1000, 0.95: 5
1000, 1.0: 5
1000, 1.05: 5
1000, 1.1: 0
1125.0, 0.1: 5
1125.0, 0.15: 5
1125.0, 0.2: 5
1125.0, 0.25: 5
1125.0, 0.3: 5
1125.0, 0.35: 5
1125.0, 0.4: 5
1125.0, 0.45: 5
1125.0, 0.5: 5
1125.0, 0.55: 5
1125.0, 0.6: 5
1125.0, 0.65: 5
1125.0, 0.7: 5
1125.0, 0.75: 5
1125.0, 0.8: 5
1125.0, 0.85: 5
1125.0, 0.9: 5
1125.0, 0.95: 5
1125.0, 1.0: 5
1125.0, 1.05: 5
1125.0, 1.1: 5
1250.0, 0.1: 5
1250.0, 0.15: 5
1250.0, 0.2: 5
1250.0, 0.25: 5
1250.0, 0.3: 5
1250.0, 0.35: 5
1250.0, 0.4: 5
1250.0, 0.45: 5
1250.0, 0.5: 5
1250.0, 0.55: 5
1250.0, 0.6: 5
1250.0, 0.65: 5
1250.0, 0.7: 5
1250.0, 0.75: 5
1250.0, 0.8: 5
1250.0, 0.85: 5
1250.0, 0.9: 5
1250.0, 0.95: 5
1250.0, 1.0: 5
1250.0, 1.05: 5
1250.0, 1.1: 5
1375.0, 0.1: 5
1375.0, 0.15: 5
1375.0, 0.2: 5
1375.0, 0.25: 5
1375.

In [56]:
test = 'abcdefg'
print(test[-3:])

efg
